# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EPO_SUM.ui'
#
# Created: Fri Jun 28 12:21:37 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PySide6.QtWidgets import QApplication, QMenu, QWidgetAction, QPlainTextEdit, QMenuBar, QSizePolicy, QSpacerItem, QDateTimeEdit, QAbstractItemView, QMainWindow, QLineEdit, QWidget, QComboBox, QPushButton, QTableView, QLabel, QGridLayout


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(808, 674)
        # icon = QIcon()
        # icon.addPixmap(QPixmap(":/icon/IconBlue_crop.png")), QIcon.Normal, QIcon.Off)
        # MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(6.0)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(10, 340, 791, 301)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QGridLayout(self.layoutWidget)
        # self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.comboFilter = QComboBox(self.layoutWidget)
        self.comboFilter.setObjectName("comboFilter")
        self.comboFilter.addItem("")
        self.comboFilter.addItem("")
        self.gridLayout.addWidget(self.comboFilter, 0, 1, 1, 1)
        self.lineEditSearch = QLineEdit(self.layoutWidget)
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.gridLayout.addWidget(self.lineEditSearch, 0, 2, 1, 1)
        self.pushSearch = QPushButton(self.layoutWidget)
        self.pushSearch.setObjectName("pushSearch")
        self.gridLayout.addWidget(self.pushSearch, 0, 3, 1, 1)
        self.pushclearsearch = QPushButton(self.layoutWidget)
        self.pushclearsearch.setObjectName("pushclearsearch")
        self.gridLayout.addWidget(self.pushclearsearch, 0, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.tableView = QTableView(self.layoutWidget)
        self.tableView.setEditTriggers(QAbstractItemView.DoubleClicked)
        self.tableView.setTabKeyNavigation(False)
        self.tableView.setDragDropOverwriteMode(False)
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.gridLayout_2.addWidget(self.tableView, 0, 0, 1, 1)
        self.layoutWidget1 = QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(9, 4, 231, 128)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_4 = QGridLayout(self.layoutWidget1)
        # self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Host_Name_label = QLabel(self.layoutWidget1)
        self.Host_Name_label.setObjectName("Host_Name_label")
        self.gridLayout_4.addWidget(self.Host_Name_label, 0, 0, 1, 1)
        self.Hostname_Input = QLineEdit(self.layoutWidget1)
        self.Hostname_Input.setObjectName("Hostname_Input")
        self.gridLayout_4.addWidget(self.Hostname_Input, 0, 1, 1, 1)
        self.IP_label = QLabel(self.layoutWidget1)
        self.IP_label.setObjectName("IP_label")
        self.gridLayout_4.addWidget(self.IP_label, 1, 0, 1, 1)
        self.IP_Address_Input = QLineEdit(self.layoutWidget1)
        self.IP_Address_Input.setObjectName("IP_Address_Input")
        self.gridLayout_4.addWidget(self.IP_Address_Input, 1, 1, 1, 1)
        self.Username_label = QLabel(self.layoutWidget1)
        self.Username_label.setObjectName("Username_label")
        self.gridLayout_4.addWidget(self.Username_label, 2, 0, 1, 1)
        self.Username_input = QLineEdit(self.layoutWidget1)
        self.Username_input.setObjectName("Username_input")
        self.gridLayout_4.addWidget(self.Username_input, 2, 1, 1, 1)
        self.Action_label = QLabel(self.layoutWidget1)
        self.Action_label.setObjectName("Action_label")
        self.gridLayout_4.addWidget(self.Action_label, 3, 0, 1, 1)
        self.Action_selection = QComboBox(self.layoutWidget1)
        self.Action_selection.setObjectName("Action_selection")
        # self.Action_selection.setEditable(True)
        self.Action_selection.addItem("")
        self.Action_selection.addItem("")
        self.Action_selection.addItem("")
        self.Action_selection.addItem("")
        self.Action_selection.addItem("")
        self.Action_selection.addItem("")
        # self.Action_selection.addItem(""))
        self.gridLayout_4.addWidget(self.Action_selection, 3, 1, 1, 1)
        self.layoutWidget2 = QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(250, 0, 241, 128)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_5 = QGridLayout(self.layoutWidget2)
        # self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.Device_label = QLabel(self.layoutWidget2)
        self.Device_label.setObjectName("Device_label")
        self.gridLayout_5.addWidget(self.Device_label, 0, 0, 1, 1)
        self.Device_Type_Drop = QComboBox(self.layoutWidget2)
        self.Device_Type_Drop.setObjectName("Device_Type_Drop")
        self.Device_Type_Drop.addItem("")
        self.Device_Type_Drop.addItem("")
        self.Device_Type_Drop.addItem("")
        self.gridLayout_5.addWidget(self.Device_Type_Drop, 0, 1, 1, 1)
        self.label = QLabel(self.layoutWidget2)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 1, 0, 1, 1)     
        self.lineEditDAT = QLineEdit(self.layoutWidget2)
        self.lineEditDAT.setObjectName("lineEditDAT")
        self.gridLayout_5.addWidget(self.lineEditDAT, 1, 1, 1, 1)
        self.Location_label = QLabel(self.layoutWidget2)
        self.Location_label.setObjectName("Location_label")
        self.gridLayout_5.addWidget(self.Location_label, 2, 0, 1, 1)
        self.Location_input = QLineEdit(self.layoutWidget2)
        self.Location_input.setObjectName("Location_input")
        self.gridLayout_5.addWidget(self.Location_input, 2, 1, 1, 1)
        self.Detection_Type_label = QLabel(self.layoutWidget2)
        self.Detection_Type_label.setObjectName("Detection_Type_label")
        self.gridLayout_5.addWidget(self.Detection_Type_label, 3, 0, 1, 1)
        self.Detection_Type_Input = QLineEdit(self.layoutWidget2)
        self.Detection_Type_Input.setObjectName("Detection_Type_Input")
        self.gridLayout_5.addWidget(self.Detection_Type_Input, 3, 1, 1, 1)
        self.layoutWidget3 = QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(500, 0, 301, 128)
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_6 = QGridLayout(self.layoutWidget3)
        # self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.Logs_label = QLabel(self.layoutWidget3)
        self.Logs_label.setObjectName("Logs_label")
        self.gridLayout_6.addWidget(self.Logs_label, 0, 0, 1, 1)
        self.lineEditLogs = QLineEdit(self.layoutWidget3)
        self.lineEditLogs.setObjectName("lineEditLogs")
        self.gridLayout_6.addWidget(self.lineEditLogs, 0, 1, 1, 1)
        self.Date_Gen_label = QLabel(self.layoutWidget3)
        self.Date_Gen_label.setObjectName("Date_Gen_label")
        self.gridLayout_6.addWidget(self.Date_Gen_label, 1, 0, 1, 1)
        self.Date_gen_input = QDateTimeEdit(self.layoutWidget3)
        self.Date_gen_input.setWrapping(False)
        self.Date_gen_input.setFrame(True)
        # self.Date_gen_input.setDate(QDate(2013, 1, 1))
        # self.Date_gen_input.setTime(QTime(1, 0, 0))
        self.Date_gen_input.setCurrentSection(QDateTimeEdit.MonthSection)
        self.Date_gen_input.setObjectName("Date_gen_input")
        self.gridLayout_6.addWidget(self.Date_gen_input, 1, 1, 1, 1)
        self.lineEditdategen = QLineEdit(self.layoutWidget3)
        self.lineEditdategen.setObjectName("lineEditdategen")
        self.gridLayout_6.addWidget(self.lineEditdategen, 1, 1, 1, 1)
        self.Org_label = QLabel(self.layoutWidget3)
        self.Org_label.setObjectName("Org_label")
        self.gridLayout_6.addWidget(self.Org_label, 3, 0, 1, 1)
        self.Org_input = QLineEdit(self.layoutWidget3)
        self.Org_input.setObjectName("Org_input")
        self.gridLayout_6.addWidget(self.Org_input, 3, 1, 1, 1)
        self.Date_rec_input = QDateTimeEdit(self.layoutWidget3)
        # self.Date_rec_input.setDate(QDate(2013, 1, 1))
        # self.Date_rec_input.setTime(QTime(1, 0, 0))
        self.Date_rec_input.setDisplayFormat("MM/dd/yy h:mm:ss A")
        # self.Date_rec_input.setTimeSpec(Qt.LocalTime)
        self.Date_rec_input.setObjectName("Date_rec_input")
        self.gridLayout_6.addWidget(self.Date_rec_input, 2, 1, 1, 1)
        self.lineEditdaterec = QLineEdit(self.layoutWidget3)
        self.lineEditdaterec.setObjectName("lineEditdaterec")
        self.gridLayout_6.addWidget(self.lineEditdaterec, 2, 1, 1, 1)
        self.label_2 = QLabel(self.layoutWidget3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 2, 0, 1, 1)
        self.widget = QWidget(self.centralwidget)
        self.widget.setGeometry(9, 136, 791, 201)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QGridLayout(self.widget)
        # self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Comments_label = QLabel(self.widget)
        self.Comments_label.setObjectName("Comments_label")
        self.gridLayout_3.addWidget(self.Comments_label, 1, 0, 1, 1)
        self.Save_Button = QPushButton(self.widget)
        self.Save_Button.setObjectName("Save_Button")
        self.gridLayout_3.addWidget(self.Save_Button, 2, 3, 1, 1)
        self.textEditComments = QPlainTextEdit(self.widget)
        self.textEditComments.setObjectName("textEditComments")
        self.gridLayout_3.addWidget(self.textEditComments, 1, 2, 2, 1)
        self.Update_Button = QPushButton(self.widget)
        self.Update_Button.setObjectName("Update_Button")
        self.gridLayout_3.addWidget(self.Update_Button, 2, 3, 1, 1)
        spacerItem = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 1, 1, 1, 1)
        self.pushRefresh = QPushButton(self.widget)
        self.pushRefresh.setObjectName("pushRefresh")
        self.gridLayout_3.addWidget(self.pushRefresh, 2, 0, 1, 2)
        self.File_Path_input = QPlainTextEdit(self.widget)
        self.File_Path_input.setObjectName("File_Path_input")
        self.gridLayout_3.addWidget(self.File_Path_input, 0, 2, 1, 1)
        self.File_path_label = QLabel(self.widget)
        self.File_path_label.setObjectName("File_path_label")
        self.gridLayout_3.addWidget(self.File_path_label, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setGeometry(0, 0, 808, 25)
        self.menubar.setObjectName("menubar")
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuForm = QMenu(self.menubar)
        self.menuForm.setObjectName("menuForm")
        self.menuDatabase = QMenu(self.menubar)
        self.menuDatabase.setObjectName("menuDatabase")
        self.menuExport_By = QMenu(self.menuDatabase)
        self.menuExport_By.setObjectName("menuExport_By")
        MainWindow.setMenuBar(self.menubar)
        self.actionClose = QWidgetAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionOpen = QWidgetAction(MainWindow)
        self.actionOpen.setIconVisibleInMenu(False)
        self.actionOpen.setObjectName("actionOpen")
        self.actionDatabase = QWidgetAction(MainWindow)
        self.actionDatabase.setObjectName("actionDatabase")
        self.actionBy_Date = QWidgetAction(MainWindow)
        self.actionBy_Date.setObjectName("actionBy_Date")
        self.actionBy_Hostname = QWidgetAction(MainWindow)
        self.actionBy_Hostname.setObjectName("actionBy_Hostname")
        self.actionBy_Username = QWidgetAction(MainWindow)
        self.actionBy_Username.setObjectName("actionBy_Username")
        self.actionBy_Date_2 = QWidgetAction(MainWindow)
        self.actionBy_Date_2.setObjectName("actionBy_Date_2")
        self.actionBy_Hostname_2 = QWidgetAction(MainWindow)
        self.actionBy_Hostname_2.setObjectName("actionBy_Hostname_2")
        self.actionBy_Username_2 = QWidgetAction(MainWindow)
        self.actionBy_Username_2.setObjectName("actionBy_Username_2")
        self.actionBy_Date_3 = QWidgetAction(MainWindow)
        self.actionBy_Date_3.setObjectName("actionBy_Date_3")
        self.actionBy_Hostname_3 = QWidgetAction(MainWindow)
        self.actionBy_Hostname_3.setObjectName("actionBy_Hostname_3")
        self.actionBy_Username_3 = QWidgetAction(MainWindow)
        self.actionBy_Username_3.setObjectName("actionBy_Username_3")
        self.actionExport_Entire_Database = QWidgetAction(MainWindow)
        self.actionExport_Entire_Database.setObjectName("actionExport_Entire_Database")
        self.actionExport_AV_Summary = QWidgetAction(MainWindow)
        self.actionExport_Entire_Database.setObjectName("actionExport_AV_Summary")
        self.actionDelete_Row = QWidgetAction(MainWindow)
        self.actionDelete_Row.setObjectName("actionDelete_Row")
        self.actionBy_Date_4 = QWidgetAction(MainWindow)
        self.actionBy_Date_4.setObjectName("actionBy_Date_4")
        self.actionBy_Hostname_4 = QWidgetAction(MainWindow)
        self.actionBy_Hostname_4.setObjectName("actionBy_Hostname_4")
        self.actionBy_Username_4 = QWidgetAction(MainWindow)
        self.actionBy_Username_4.setObjectName("actionBy_Username_4")
        self.actionSpace = QWidgetAction(MainWindow)
        self.actionSpace.setObjectName("actionSpace")
        self.actionUpdate_Row = QWidgetAction(MainWindow)
        self.actionUpdate_Row.setObjectName("actionUpdate_Row")
        self.actionClear_Form = QWidgetAction(MainWindow)
        self.actionClear_Form.setObjectName("actionClear_Form")
        self.menuFile.addAction(self.actionClose)
        self.menuExport_By.addAction(self.actionBy_Date_4)
        self.menuExport_By.addAction(self.actionBy_Hostname_4)
        self.menuExport_By.addAction(self.actionBy_Username_4)
        self.menuDatabase.addAction(self.actionUpdate_Row)
        self.menuDatabase.addSeparator()
        self.menuDatabase.addAction(self.actionExport_Entire_Database)
        self.menuDatabase.addSeparator()
        self.menuDatabase.addAction(self.actionExport_AV_Summary)
        self.menuDatabase.addSeparator()
        self.menuDatabase.addAction(self.menuExport_By.menuAction())
        self.menuDatabase.addSeparator()
        self.menuForm.addAction(self.actionClear_Form)
        self.menuDatabase.addAction(self.actionDelete_Row)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDatabase.menuAction())
        self.menubar.addAction(self.menuForm.menuAction())


        self.retranslateUi(MainWindow)
        # QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.Hostname_Input, self.Device_Type_Drop)
        MainWindow.setTabOrder(self.Device_Type_Drop, self.IP_Address_Input)
        MainWindow.setTabOrder(self.IP_Address_Input, self.lineEditDAT)
        MainWindow.setTabOrder(self.lineEditDAT, self.Date_gen_input)
        MainWindow.setTabOrder(self.Date_gen_input, self.Username_input)
        MainWindow.setTabOrder(self.Username_input, self.Location_input)
        MainWindow.setTabOrder(self.Location_input, self.Date_rec_input)
        MainWindow.setTabOrder(self.Date_rec_input, self.Action_selection)
        MainWindow.setTabOrder(self.Action_selection, self.Detection_Type_Input)
        MainWindow.setTabOrder(self.Detection_Type_Input, self.Org_input)
        MainWindow.setTabOrder(self.Org_input, self.Save_Button)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QApplication.translate("MainWindow", "AV Summary", None))
        self.pushSearch.setText(QApplication.translate("MainWindow", "Search", None))
        self.label_3.setText(QApplication.translate("MainWindow", "Find:", None))
        self.comboFilter.setItemText(0, QApplication.translate("MainWindow", "Hostname", None))
        self.comboFilter.setItemText(1, QApplication.translate("MainWindow", "Username", None))
        self.Host_Name_label.setText(QApplication.translate("MainWindow", "Host Name", None))
        self.Hostname_Input.setToolTip(QApplication.translate("MainWindow", "<html><head/><body><p>Enter Hostname</p></body></html>", None))
        self.IP_label.setText(QApplication.translate("MainWindow", "IP Address", None))
        self.IP_Address_Input.setToolTip(QApplication.translate("MainWindow", "<html><head/><body><p>Enter IP Address</p></body></html>", None))
        self.Username_label.setText(QApplication.translate("MainWindow", "Username", None))
        self.Username_input.setToolTip(QApplication.translate("MainWindow", "<html><head/><body><p>Input the username.</p></body></html>", None))
        self.Action_label.setText(QApplication.translate("MainWindow", "Action", None))
        self.Action_selection.setToolTip(QApplication.translate("MainWindow", "<html><head/><body><p>Select the action taken.</p></body></html>", None))
        self.Action_selection.setItemText(0, QApplication.translate("MainWindow", "On Access Deleted", None))
        self.Action_selection.setItemText(1, QApplication.translate("MainWindow", "On Access Cleaned", None))
        self.Action_selection.setItemText(2, QApplication.translate("MainWindow", "Managed Scan Deleted", None))
        self.Action_selection.setItemText(3, QApplication.translate("MainWindow", "Managed Scan Cleaned", None))
        self.Action_selection.setItemText(4, QApplication.translate("MainWindow", "Script Scan Blocked", None))
        self.Action_selection.setItemText(5, QApplication.translate("MainWindow", "Other", None))
        self.Device_label.setText(QApplication.translate("MainWindow", "Device Type", None))
        self.Device_Type_Drop.setToolTip(QApplication.translate("MainWindow", "<html><head/><body><p>Select Device Type</p></body></html>", None))
        self.Device_Type_Drop.setItemText(0, QApplication.translate("MainWindow", "Desktop", None))
        self.Device_Type_Drop.setItemText(1, QApplication.translate("MainWindow", "Laptop", None))
        self.Device_Type_Drop.setItemText(2, QApplication.translate("MainWindow", "Server", None))
        self.label.setText(QApplication.translate("MainWindow", "Dat Version", None))
        self.lineEditDAT.setToolTip(QApplication.translate("MainWindow", "<html><head/><body><p>Enter the DAT Version.</p></body></html>", None))
        self.Location_label.setText(QApplication.translate("MainWindow", "Location", None))
        self.Location_input.setToolTip(QApplication.translate("MainWindow", "<html><head/><body><p>Enter the location of the user.</p></body></html>", None))
        self.Detection_Type_label.setText(QApplication.translate("MainWindow", "Detection Type", None))
        self.Detection_Type_Input.setToolTip(QApplication.translate("MainWindow", "<html><head/><body><p>Enter the detection type.</p></body></html>", None))
        self.Logs_label.setText(QApplication.translate("MainWindow", "Logs Pulled", None))
        self.Date_Gen_label.setText(QApplication.translate("MainWindow", "Date/time Gen.", None))
        self.Date_gen_input.setToolTip(QApplication.translate("MainWindow", "<html><head/><body><p>Enter Date and Time Event was Generated.</p></body></html>", None))
        self.Date_gen_input.setDisplayFormat(QApplication.translate("MainWindow", "MM/dd/yy h:mm:ss A", None))
        self.Org_label.setText(QApplication.translate("MainWindow", "Organization", None))
        self.Org_input.setToolTip(QApplication.translate("MainWindow", "<html><head/><body><p>Enter The Orginization</p></body></html>", None))
        self.Date_rec_input.setToolTip(QApplication.translate("MainWindow", "<html><head/><body><p>Enter Date and Time Event was Received.</p></body></html>", None))
        self.label_2.setText(QApplication.translate("MainWindow", "Date/Time Rec.", None))
        self.Comments_label.setText(QApplication.translate("MainWindow", "Comments", None))
        self.Save_Button.setToolTip(QApplication.translate("MainWindow", "<html><head/><body><p>Save and update the AV summary database.</p></body></html>", None))
        self.Save_Button.setText(QApplication.translate("MainWindow", "Save", None))
        self.Update_Button.setText(QApplication.translate("MainWindow", "Update", None))
        self.pushRefresh.setText(QApplication.translate("MainWindow", "Refresh", None))
        self.File_path_label.setText(QApplication.translate("MainWindow", "File Path", None))
        self.menuFile.setTitle(QApplication.translate("MainWindow", "File", None))
        self.menuForm.setTitle(QApplication.translate("MainWindow", "Form", None))
        self.menuDatabase.setTitle(QApplication.translate("MainWindow", "Database", None))
        self.menuExport_By.setTitle(QApplication.translate("MainWindow", "Export By", None))
        self.actionClose.setText(QApplication.translate("MainWindow", "Close", None))
        self.actionOpen.setText(QApplication.translate("MainWindow", "Open", None))
        self.actionDatabase.setText(QApplication.translate("MainWindow", "Database", None))
        self.actionBy_Date.setText(QApplication.translate("MainWindow", "By Date", None))
        self.actionBy_Hostname.setText(QApplication.translate("MainWindow", "By Hostname", None))
        self.actionBy_Username.setText(QApplication.translate("MainWindow", "By Username", None))
        self.actionBy_Date_2.setText(QApplication.translate("MainWindow", "By Date", None))
        self.actionBy_Hostname_2.setText(QApplication.translate("MainWindow", "By Hostname", None))
        self.actionBy_Username_2.setText(QApplication.translate("MainWindow", "By Username", None))
        self.actionBy_Date_3.setText(QApplication.translate("MainWindow", "By Date", None))
        self.actionBy_Hostname_3.setText(QApplication.translate("MainWindow", "By Hostname", None))
        self.actionBy_Username_3.setText(QApplication.translate("MainWindow", "By Username", None))
        self.actionExport_Entire_Database.setText(QApplication.translate("MainWindow", "Export Entire Database", None))
        self.actionClear_Form.setText(QApplication.translate("MainWindow", "Clear Form", None))
        self.actionDelete_Row.setText(QApplication.translate("MainWindow", "Delete Row", None))
        self.actionBy_Date_4.setText(QApplication.translate("MainWindow", "Date Received", None))
        self.actionBy_Hostname_4.setText(QApplication.translate("MainWindow", "Hostname", None))
        self.actionBy_Username_4.setText(QApplication.translate("MainWindow", "Username", None))
        self.actionSpace.setText(QApplication.translate("MainWindow", "space", None))
        self.actionUpdate_Row.setText(QApplication.translate("MainWindow", "Update Row", None))
        self.actionExport_AV_Summary.setText(QApplication.translate("MainWindow", "Export AV Summary", None))
        self.pushclearsearch.setText(QApplication.translate("MainWindow", "Clear", None))

if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

