# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EPO_SUM.ui'
#
# Created: Fri Jun 28 12:21:37 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(808, 674)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/IconBlue_crop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(6.0)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 340, 791, 301))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.comboFilter = QtGui.QComboBox(self.layoutWidget)
        self.comboFilter.setObjectName(_fromUtf8("comboFilter"))
        self.comboFilter.addItem(_fromUtf8(""))
        self.comboFilter.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboFilter, 0, 1, 1, 1)
        self.lineEditSearch = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditSearch.setObjectName(_fromUtf8("lineEditSearch"))
        self.gridLayout.addWidget(self.lineEditSearch, 0, 2, 1, 1)
        self.pushSearch = QtGui.QPushButton(self.layoutWidget)
        self.pushSearch.setObjectName(_fromUtf8("pushSearch"))
        self.gridLayout.addWidget(self.pushSearch, 0, 3, 1, 1)
        self.pushclearsearch = QtGui.QPushButton(self.layoutWidget)
        self.pushclearsearch.setObjectName(_fromUtf8("pushclearsearch"))
        self.gridLayout.addWidget(self.pushclearsearch, 0, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.tableView = QtGui.QTableView(self.layoutWidget)
        self.tableView.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.tableView.setTabKeyNavigation(False)
        self.tableView.setDragDropOverwriteMode(False)
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.gridLayout_2.addWidget(self.tableView, 0, 0, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(9, 4, 231, 128))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.Host_Name_label = QtGui.QLabel(self.layoutWidget1)
        self.Host_Name_label.setObjectName(_fromUtf8("Host_Name_label"))
        self.gridLayout_4.addWidget(self.Host_Name_label, 0, 0, 1, 1)
        self.Hostname_Input = QtGui.QLineEdit(self.layoutWidget1)
        self.Hostname_Input.setObjectName(_fromUtf8("Hostname_Input"))
        self.gridLayout_4.addWidget(self.Hostname_Input, 0, 1, 1, 1)
        self.IP_label = QtGui.QLabel(self.layoutWidget1)
        self.IP_label.setObjectName(_fromUtf8("IP_label"))
        self.gridLayout_4.addWidget(self.IP_label, 1, 0, 1, 1)
        self.IP_Address_Input = QtGui.QLineEdit(self.layoutWidget1)
        self.IP_Address_Input.setObjectName(_fromUtf8("IP_Address_Input"))
        self.gridLayout_4.addWidget(self.IP_Address_Input, 1, 1, 1, 1)
        self.Username_label = QtGui.QLabel(self.layoutWidget1)
        self.Username_label.setObjectName(_fromUtf8("Username_label"))
        self.gridLayout_4.addWidget(self.Username_label, 2, 0, 1, 1)
        self.Username_input = QtGui.QLineEdit(self.layoutWidget1)
        self.Username_input.setObjectName(_fromUtf8("Username_input"))
        self.gridLayout_4.addWidget(self.Username_input, 2, 1, 1, 1)
        self.Action_label = QtGui.QLabel(self.layoutWidget1)
        self.Action_label.setObjectName(_fromUtf8("Action_label"))
        self.gridLayout_4.addWidget(self.Action_label, 3, 0, 1, 1)
        self.Action_selection = QtGui.QComboBox(self.layoutWidget1)
        self.Action_selection.setObjectName(_fromUtf8("Action_selection"))
        # self.Action_selection.setEditable(True)
        self.Action_selection.addItem(_fromUtf8(""))
        self.Action_selection.addItem(_fromUtf8(""))
        self.Action_selection.addItem(_fromUtf8(""))
        self.Action_selection.addItem(_fromUtf8(""))
        self.Action_selection.addItem(_fromUtf8(""))
        self.Action_selection.addItem(_fromUtf8(""))
        # self.Action_selection.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.Action_selection, 3, 1, 1, 1)
        self.layoutWidget2 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(250, 0, 241, 128))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.Device_label = QtGui.QLabel(self.layoutWidget2)
        self.Device_label.setObjectName(_fromUtf8("Device_label"))
        self.gridLayout_5.addWidget(self.Device_label, 0, 0, 1, 1)
        self.Device_Type_Drop = QtGui.QComboBox(self.layoutWidget2)
        self.Device_Type_Drop.setObjectName(_fromUtf8("Device_Type_Drop"))
        self.Device_Type_Drop.addItem(_fromUtf8(""))
        self.Device_Type_Drop.addItem(_fromUtf8(""))
        self.Device_Type_Drop.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.Device_Type_Drop, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_5.addWidget(self.label, 1, 0, 1, 1)     
        self.lineEditDAT = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEditDAT.setObjectName(_fromUtf8("lineEditDAT"))
        self.gridLayout_5.addWidget(self.lineEditDAT, 1, 1, 1, 1)
        self.Location_label = QtGui.QLabel(self.layoutWidget2)
        self.Location_label.setObjectName(_fromUtf8("Location_label"))
        self.gridLayout_5.addWidget(self.Location_label, 2, 0, 1, 1)
        self.Location_input = QtGui.QLineEdit(self.layoutWidget2)
        self.Location_input.setObjectName(_fromUtf8("Location_input"))
        self.gridLayout_5.addWidget(self.Location_input, 2, 1, 1, 1)
        self.Detection_Type_label = QtGui.QLabel(self.layoutWidget2)
        self.Detection_Type_label.setObjectName(_fromUtf8("Detection_Type_label"))
        self.gridLayout_5.addWidget(self.Detection_Type_label, 3, 0, 1, 1)
        self.Detection_Type_Input = QtGui.QLineEdit(self.layoutWidget2)
        self.Detection_Type_Input.setObjectName(_fromUtf8("Detection_Type_Input"))
        self.gridLayout_5.addWidget(self.Detection_Type_Input, 3, 1, 1, 1)
        self.layoutWidget3 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(500, 0, 301, 128))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.gridLayout_6 = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.Logs_label = QtGui.QLabel(self.layoutWidget3)
        self.Logs_label.setObjectName(_fromUtf8("Logs_label"))
        self.gridLayout_6.addWidget(self.Logs_label, 0, 0, 1, 1)
        self.lineEditLogs = QtGui.QLineEdit(self.layoutWidget3)
        self.lineEditLogs.setObjectName(_fromUtf8("lineEditLogs"))
        self.gridLayout_6.addWidget(self.lineEditLogs, 0, 1, 1, 1)
        self.Date_Gen_label = QtGui.QLabel(self.layoutWidget3)
        self.Date_Gen_label.setObjectName(_fromUtf8("Date_Gen_label"))
        self.gridLayout_6.addWidget(self.Date_Gen_label, 1, 0, 1, 1)
        self.Date_gen_input = QtGui.QDateTimeEdit(self.layoutWidget3)
        self.Date_gen_input.setWrapping(False)
        self.Date_gen_input.setFrame(True)
        self.Date_gen_input.setDate(QtCore.QDate(2013, 1, 1))
        self.Date_gen_input.setTime(QtCore.QTime(1, 0, 0))
        self.Date_gen_input.setCurrentSection(QtGui.QDateTimeEdit.MonthSection)
        self.Date_gen_input.setObjectName(_fromUtf8("Date_gen_input"))
        self.gridLayout_6.addWidget(self.Date_gen_input, 1, 1, 1, 1)
        self.lineEditdategen = QtGui.QLineEdit(self.layoutWidget3)
        self.lineEditdategen.setObjectName(_fromUtf8("lineEditdategen"))
        self.gridLayout_6.addWidget(self.lineEditdategen, 1, 1, 1, 1)
        self.Org_label = QtGui.QLabel(self.layoutWidget3)
        self.Org_label.setObjectName(_fromUtf8("Org_label"))
        self.gridLayout_6.addWidget(self.Org_label, 3, 0, 1, 1)
        self.Org_input = QtGui.QLineEdit(self.layoutWidget3)
        self.Org_input.setObjectName(_fromUtf8("Org_input"))
        self.gridLayout_6.addWidget(self.Org_input, 3, 1, 1, 1)
        self.Date_rec_input = QtGui.QDateTimeEdit(self.layoutWidget3)
        self.Date_rec_input.setDate(QtCore.QDate(2013, 1, 1))
        self.Date_rec_input.setTime(QtCore.QTime(1, 0, 0))
        self.Date_rec_input.setDisplayFormat(_fromUtf8("MM/dd/yy h:mm:ss A"))
        self.Date_rec_input.setTimeSpec(QtCore.Qt.LocalTime)
        self.Date_rec_input.setObjectName(_fromUtf8("Date_rec_input"))
        self.gridLayout_6.addWidget(self.Date_rec_input, 2, 1, 1, 1)
        self.lineEditdaterec = QtGui.QLineEdit(self.layoutWidget3)
        self.lineEditdaterec.setObjectName(_fromUtf8("lineEditdaterec"))
        self.gridLayout_6.addWidget(self.lineEditdaterec, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_6.addWidget(self.label_2, 2, 0, 1, 1)
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(9, 136, 791, 201))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.widget)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.Comments_label = QtGui.QLabel(self.widget)
        self.Comments_label.setObjectName(_fromUtf8("Comments_label"))
        self.gridLayout_3.addWidget(self.Comments_label, 1, 0, 1, 1)
        self.Save_Button = QtGui.QPushButton(self.widget)
        self.Save_Button.setObjectName(_fromUtf8("Save_Button"))
        self.gridLayout_3.addWidget(self.Save_Button, 2, 3, 1, 1)
        self.textEditComments = QtGui.QPlainTextEdit(self.widget)
        self.textEditComments.setObjectName(_fromUtf8("textEditComments"))
        self.gridLayout_3.addWidget(self.textEditComments, 1, 2, 2, 1)
        self.Update_Button = QtGui.QPushButton(self.widget)
        self.Update_Button.setObjectName(_fromUtf8("Update_Button"))
        self.gridLayout_3.addWidget(self.Update_Button, 2, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 1, 1, 1, 1)
        self.pushRefresh = QtGui.QPushButton(self.widget)
        self.pushRefresh.setObjectName(_fromUtf8("pushRefresh"))
        self.gridLayout_3.addWidget(self.pushRefresh, 2, 0, 1, 2)
        self.File_Path_input = QtGui.QPlainTextEdit(self.widget)
        self.File_Path_input.setObjectName(_fromUtf8("File_Path_input"))
        self.gridLayout_3.addWidget(self.File_Path_input, 0, 2, 1, 1)
        self.File_path_label = QtGui.QLabel(self.widget)
        self.File_path_label.setObjectName(_fromUtf8("File_path_label"))
        self.gridLayout_3.addWidget(self.File_path_label, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 808, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuForm = QtGui.QMenu(self.menubar)
        self.menuForm.setObjectName(_fromUtf8("menuForm"))
        self.menuDatabase = QtGui.QMenu(self.menubar)
        self.menuDatabase.setObjectName(_fromUtf8("menuDatabase"))
        self.menuExport_By = QtGui.QMenu(self.menuDatabase)
        self.menuExport_By.setObjectName(_fromUtf8("menuExport_By"))
        MainWindow.setMenuBar(self.menubar)
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setIconVisibleInMenu(False)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionDatabase = QtGui.QAction(MainWindow)
        self.actionDatabase.setObjectName(_fromUtf8("actionDatabase"))
        self.actionBy_Date = QtGui.QAction(MainWindow)
        self.actionBy_Date.setObjectName(_fromUtf8("actionBy_Date"))
        self.actionBy_Hostname = QtGui.QAction(MainWindow)
        self.actionBy_Hostname.setObjectName(_fromUtf8("actionBy_Hostname"))
        self.actionBy_Username = QtGui.QAction(MainWindow)
        self.actionBy_Username.setObjectName(_fromUtf8("actionBy_Username"))
        self.actionBy_Date_2 = QtGui.QAction(MainWindow)
        self.actionBy_Date_2.setObjectName(_fromUtf8("actionBy_Date_2"))
        self.actionBy_Hostname_2 = QtGui.QAction(MainWindow)
        self.actionBy_Hostname_2.setObjectName(_fromUtf8("actionBy_Hostname_2"))
        self.actionBy_Username_2 = QtGui.QAction(MainWindow)
        self.actionBy_Username_2.setObjectName(_fromUtf8("actionBy_Username_2"))
        self.actionBy_Date_3 = QtGui.QAction(MainWindow)
        self.actionBy_Date_3.setObjectName(_fromUtf8("actionBy_Date_3"))
        self.actionBy_Hostname_3 = QtGui.QAction(MainWindow)
        self.actionBy_Hostname_3.setObjectName(_fromUtf8("actionBy_Hostname_3"))
        self.actionBy_Username_3 = QtGui.QAction(MainWindow)
        self.actionBy_Username_3.setObjectName(_fromUtf8("actionBy_Username_3"))
        self.actionExport_Entire_Database = QtGui.QAction(MainWindow)
        self.actionExport_Entire_Database.setObjectName(_fromUtf8("actionExport_Entire_Database"))
        self.actionExport_AV_Summary = QtGui.QAction(MainWindow)
        self.actionExport_Entire_Database.setObjectName(_fromUtf8("actionExport_AV_Summary"))
        self.actionDelete_Row = QtGui.QAction(MainWindow)
        self.actionDelete_Row.setObjectName(_fromUtf8("actionDelete_Row"))
        self.actionBy_Date_4 = QtGui.QAction(MainWindow)
        self.actionBy_Date_4.setObjectName(_fromUtf8("actionBy_Date_4"))
        self.actionBy_Hostname_4 = QtGui.QAction(MainWindow)
        self.actionBy_Hostname_4.setObjectName(_fromUtf8("actionBy_Hostname_4"))
        self.actionBy_Username_4 = QtGui.QAction(MainWindow)
        self.actionBy_Username_4.setObjectName(_fromUtf8("actionBy_Username_4"))
        self.actionSpace = QtGui.QAction(MainWindow)
        self.actionSpace.setObjectName(_fromUtf8("actionSpace"))
        self.actionUpdate_Row = QtGui.QAction(MainWindow)
        self.actionUpdate_Row.setObjectName(_fromUtf8("actionUpdate_Row"))
        self.actionClear_Form = QtGui.QAction(MainWindow)
        self.actionClear_Form.setObjectName(_fromUtf8("actionClear_Form"))
        self.menuFile.addAction(self.actionClose)
        self.menuExport_By.addAction(self.actionBy_Date_4)
        self.menuExport_By.addAction(self.actionBy_Hostname_4)
        self.menuExport_By.addAction(self.actionBy_Username_4)
        self.menuDatabase.addAction(self.actionUpdate_Row)
        self.menuDatabase.addSeparator()
        self.menuDatabase.addAction(self.actionExport_Entire_Database)
        self.menuDatabase.addSeparator()
        self.menuDatabase.addAction(self.actionExport_AV_Summary)
        self.menuDatabase.addSeparator()
        self.menuDatabase.addAction(self.menuExport_By.menuAction())
        self.menuDatabase.addSeparator()
        self.menuForm.addAction(self.actionClear_Form)
        self.menuDatabase.addAction(self.actionDelete_Row)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDatabase.menuAction())
        self.menubar.addAction(self.menuForm.menuAction())


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.Hostname_Input, self.Device_Type_Drop)
        MainWindow.setTabOrder(self.Device_Type_Drop, self.IP_Address_Input)
        MainWindow.setTabOrder(self.IP_Address_Input, self.lineEditDAT)
        MainWindow.setTabOrder(self.lineEditDAT, self.Date_gen_input)
        MainWindow.setTabOrder(self.Date_gen_input, self.Username_input)
        MainWindow.setTabOrder(self.Username_input, self.Location_input)
        MainWindow.setTabOrder(self.Location_input, self.Date_rec_input)
        MainWindow.setTabOrder(self.Date_rec_input, self.Action_selection)
        MainWindow.setTabOrder(self.Action_selection, self.Detection_Type_Input)
        MainWindow.setTabOrder(self.Detection_Type_Input, self.Org_input)
        MainWindow.setTabOrder(self.Org_input, self.Save_Button)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "AV Summary", None, QtGui.QApplication.UnicodeUTF8))
        self.pushSearch.setText(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Find:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboFilter.setItemText(0, QtGui.QApplication.translate("MainWindow", "Hostname", None, QtGui.QApplication.UnicodeUTF8))
        self.comboFilter.setItemText(1, QtGui.QApplication.translate("MainWindow", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.Host_Name_label.setText(QtGui.QApplication.translate("MainWindow", "Host Name", None, QtGui.QApplication.UnicodeUTF8))
        self.Hostname_Input.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Enter Hostname</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.IP_label.setText(QtGui.QApplication.translate("MainWindow", "IP Address", None, QtGui.QApplication.UnicodeUTF8))
        self.IP_Address_Input.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Enter IP Address</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.Username_label.setText(QtGui.QApplication.translate("MainWindow", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.Username_input.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Input the username.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.Action_label.setText(QtGui.QApplication.translate("MainWindow", "Action", None, QtGui.QApplication.UnicodeUTF8))
        self.Action_selection.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Select the action taken.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.Action_selection.setItemText(0, QtGui.QApplication.translate("MainWindow", "On Access Deleted", None, QtGui.QApplication.UnicodeUTF8))
        self.Action_selection.setItemText(1, QtGui.QApplication.translate("MainWindow", "On Access Cleaned", None, QtGui.QApplication.UnicodeUTF8))
        self.Action_selection.setItemText(2, QtGui.QApplication.translate("MainWindow", "Managed Scan Deleted", None, QtGui.QApplication.UnicodeUTF8))
        self.Action_selection.setItemText(3, QtGui.QApplication.translate("MainWindow", "Managed Scan Cleaned", None, QtGui.QApplication.UnicodeUTF8))
        self.Action_selection.setItemText(4, QtGui.QApplication.translate("MainWindow", "Script Scan Blocked", None, QtGui.QApplication.UnicodeUTF8))
        self.Action_selection.setItemText(5, QtGui.QApplication.translate("MainWindow", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.Device_label.setText(QtGui.QApplication.translate("MainWindow", "Device Type", None, QtGui.QApplication.UnicodeUTF8))
        self.Device_Type_Drop.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Select Device Type</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.Device_Type_Drop.setItemText(0, QtGui.QApplication.translate("MainWindow", "Desktop", None, QtGui.QApplication.UnicodeUTF8))
        self.Device_Type_Drop.setItemText(1, QtGui.QApplication.translate("MainWindow", "Laptop", None, QtGui.QApplication.UnicodeUTF8))
        self.Device_Type_Drop.setItemText(2, QtGui.QApplication.translate("MainWindow", "Server", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Dat Version", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditDAT.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Enter the DAT Version.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.Location_label.setText(QtGui.QApplication.translate("MainWindow", "Location", None, QtGui.QApplication.UnicodeUTF8))
        self.Location_input.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Enter the location of the user.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.Detection_Type_label.setText(QtGui.QApplication.translate("MainWindow", "Detection Type", None, QtGui.QApplication.UnicodeUTF8))
        self.Detection_Type_Input.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Enter the detection type.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.Logs_label.setText(QtGui.QApplication.translate("MainWindow", "Logs Pulled", None, QtGui.QApplication.UnicodeUTF8))
        self.Date_Gen_label.setText(QtGui.QApplication.translate("MainWindow", "Date/time Gen.", None, QtGui.QApplication.UnicodeUTF8))
        self.Date_gen_input.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Enter Date and Time Event was Generated.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.Date_gen_input.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "MM/dd/yy h:mm:ss A", None, QtGui.QApplication.UnicodeUTF8))
        self.Org_label.setText(QtGui.QApplication.translate("MainWindow", "Organization", None, QtGui.QApplication.UnicodeUTF8))
        self.Org_input.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Enter The Orginization</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.Date_rec_input.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Enter Date and Time Event was Received.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Date/Time Rec.", None, QtGui.QApplication.UnicodeUTF8))
        self.Comments_label.setText(QtGui.QApplication.translate("MainWindow", "Comments", None, QtGui.QApplication.UnicodeUTF8))
        self.Save_Button.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Save and update the AV summary database.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.Save_Button.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.Update_Button.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.pushRefresh.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.File_path_label.setText(QtGui.QApplication.translate("MainWindow", "File Path", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuForm.setTitle(QtGui.QApplication.translate("MainWindow", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDatabase.setTitle(QtGui.QApplication.translate("MainWindow", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.menuExport_By.setTitle(QtGui.QApplication.translate("MainWindow", "Export By", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDatabase.setText(QtGui.QApplication.translate("MainWindow", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBy_Date.setText(QtGui.QApplication.translate("MainWindow", "By Date", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBy_Hostname.setText(QtGui.QApplication.translate("MainWindow", "By Hostname", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBy_Username.setText(QtGui.QApplication.translate("MainWindow", "By Username", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBy_Date_2.setText(QtGui.QApplication.translate("MainWindow", "By Date", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBy_Hostname_2.setText(QtGui.QApplication.translate("MainWindow", "By Hostname", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBy_Username_2.setText(QtGui.QApplication.translate("MainWindow", "By Username", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBy_Date_3.setText(QtGui.QApplication.translate("MainWindow", "By Date", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBy_Hostname_3.setText(QtGui.QApplication.translate("MainWindow", "By Hostname", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBy_Username_3.setText(QtGui.QApplication.translate("MainWindow", "By Username", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_Entire_Database.setText(QtGui.QApplication.translate("MainWindow", "Export Entire Database", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_Form.setText(QtGui.QApplication.translate("MainWindow", "Clear Form", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete_Row.setText(QtGui.QApplication.translate("MainWindow", "Delete Row", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBy_Date_4.setText(QtGui.QApplication.translate("MainWindow", "Date Received", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBy_Hostname_4.setText(QtGui.QApplication.translate("MainWindow", "Hostname", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBy_Username_4.setText(QtGui.QApplication.translate("MainWindow", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpace.setText(QtGui.QApplication.translate("MainWindow", "space", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdate_Row.setText(QtGui.QApplication.translate("MainWindow", "Update Row", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_AV_Summary.setText(QtGui.QApplication.translate("MainWindow", "Export AV Summary", None, QtGui.QApplication.UnicodeUTF8))
        self.pushclearsearch.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

